apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sob
resources:
  - namespace.yaml
  - client-deployment.yaml
  - client-service.yaml
  - author-deployment.yaml
  - author-service.yaml
  - redis-session.yaml 