apiVersion: v1
kind: Secret
metadata:
  name: sob-client-env
  namespace: sob
type: Opaque
stringData:
  PORT: "3000"
  DB_HOST: "your-rds-hostname"
  DB_PORT: "5432"
  DB_NAME: "your-db-name"
  DB_USER: "your-db-user"
  DB_PASSWORD: "your-db-password"
  DB_SSL: "true"
  AWS_REGION: "eu-west-2"
  S3_BUCKET_NAME: "your-public-bucket"
  AWS_ACCESS_KEY_ID: "your-access-key-id"
  AWS_SECRET_ACCESS_KEY: "your-secret-access-key"
  SSM_SESSION_SECRET_PATH: "sob-sec-session"
  MAX_FILE_SIZE_MB: "10"
